/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Paneles;

import Modelo.DetalleCarrito;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JOptionPane;

/**
 * @author Rosales paez /Martinez Barradas
 * @version 1.5
 * fecha:12 octubre 2017*/
public class JPanelCarrito extends javax.swing.JPanel {

    DetalleCarrito dC;
    ArrayList<DetalleCarrito> carrito;
    int indice;
    String codigo;
    DetalleCarrito detCarri;
    boolean bandera = false;

    /**
     * Creates new form JPanelAgregar
     */
    public JPanelCarrito(ArrayList<DetalleCarrito> carrito) {
        initComponents();
        this.carrito = carrito;
        lbTotal.setText("" + Total());
    }

    public void VerElemento(String codigo, String titulo, int cantidad, float precio, float subtotal, int indice) {
        this.codigo = codigo;
        lbCodigo.setText(String.valueOf(codigo));
        lbTitulo.setText(String.valueOf(titulo));
        txtCantidad.setText("" + cantidad);
        lbPrecio.setText("" + precio);
        lbSubtotal.setText("" + subtotal);
        bandera = true;
        this.indice = indice;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbCodigo = new javax.swing.JLabel();
        lbTitulo = new javax.swing.JLabel();
        lbCantidad = new javax.swing.JLabel();
        btnAgregarPelicula = new javax.swing.JButton();
        txtCantidad = new javax.swing.JTextField();
        lbCodigo1 = new javax.swing.JLabel();
        lbTitulo1 = new javax.swing.JLabel();
        lbPrecio2 = new javax.swing.JLabel();
        lbSubtotal = new javax.swing.JLabel();
        lbPrecio1 = new javax.swing.JLabel();
        lbPrecio = new javax.swing.JLabel();
        lbPrecio3 = new javax.swing.JLabel();
        lbTotal = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbCodigo.setFont(new java.awt.Font("Arial Black", 2, 14)); // NOI18N
        lbCodigo.setText("________");

        lbTitulo.setFont(new java.awt.Font("Arial Black", 2, 14)); // NOI18N
        lbTitulo.setText("________");

        lbCantidad.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        lbCantidad.setText("Editar cantidad:");

        btnAgregarPelicula.setText("Editar");
        btnAgregarPelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarPeliculaActionPerformed(evt);
            }
        });

        txtCantidad.setText("0");

        lbCodigo1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        lbCodigo1.setText("Codigo:");

        lbTitulo1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        lbTitulo1.setText("Titulo:");

        lbPrecio2.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        lbPrecio2.setText("Subtotal:");

        lbSubtotal.setFont(new java.awt.Font("Arial Black", 2, 14)); // NOI18N
        lbSubtotal.setText("________");

        lbPrecio1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        lbPrecio1.setText("Precio:");

        lbPrecio.setFont(new java.awt.Font("Arial Black", 2, 14)); // NOI18N
        lbPrecio.setText("________");

        lbPrecio3.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        lbPrecio3.setText("Total:");

        lbTotal.setFont(new java.awt.Font("Arial Black", 2, 14)); // NOI18N
        lbTotal.setText("________");

        jButton1.setText("Finalizar Compra");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCantidad)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbCantidad)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbPrecio2)
                                .addGap(76, 76, 76)
                                .addComponent(lbSubtotal))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbTitulo1)
                                    .addComponent(lbCodigo1)
                                    .addComponent(lbPrecio1))
                                .addGap(76, 76, 76)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbPrecio)
                                    .addComponent(lbTitulo)
                                    .addComponent(lbCodigo))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(btnAgregarPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(141, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbPrecio3)
                        .addGap(76, 76, 76)
                        .addComponent(lbTotal)))
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbCodigo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbCodigo1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbTitulo1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbPrecio)
                    .addComponent(lbPrecio1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbCantidad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbSubtotal)
                    .addComponent(lbPrecio2))
                .addGap(33, 33, 33)
                .addComponent(btnAgregarPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 272, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbTotal)
                    .addComponent(lbPrecio3))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents

    public ArrayList<DetalleCarrito> RetornaCarrito() {
        return carrito;
    }

    public void agregarDetCarrito() {

        carrito.remove(indice);

        int cantidad = Integer.parseInt(txtCantidad.getText());
        String nombre = lbTitulo.getText();
        float precio = Float.parseFloat(lbPrecio.getText());

        float subtotal = (float) cantidad * precio;
        dC = new DetalleCarrito(codigo, nombre, cantidad, precio, subtotal);
        carrito.add(dC);

    }

    public float Total() {
        float total = 0;

        Iterator<DetalleCarrito> detPeli = carrito.iterator();
        while (detPeli.hasNext()) {
            detCarri = detPeli.next();
            total += detCarri.getSubtotal();
        }

        return total;
    }

    private void btnAgregarPeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarPeliculaActionPerformed
        if (bandera) {
            agregarDetCarrito();
            JOptionPane.showMessageDialog(null, "editado Corectamente", "Agregado", JOptionPane.NO_OPTION);
            bandera = false;
        } else {
            JOptionPane.showMessageDialog(null, "Selecciona una", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAgregarPeliculaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarPelicula;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lbCantidad;
    private javax.swing.JLabel lbCodigo;
    private javax.swing.JLabel lbCodigo1;
    private javax.swing.JLabel lbPrecio;
    private javax.swing.JLabel lbPrecio1;
    private javax.swing.JLabel lbPrecio2;
    private javax.swing.JLabel lbPrecio3;
    private javax.swing.JLabel lbSubtotal;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JLabel lbTitulo1;
    private javax.swing.JLabel lbTotal;
    private javax.swing.JTextField txtCantidad;
    // End of variables declaration//GEN-END:variables
}
